'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { DragDropContext, Droppable, Draggable, DropResult } from '@hello-pangea/dnd';
import { 
  BarChart, Bar, LineChart, Line, AreaChart, Area, PieChart, Pie, Cell, 
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend
} from 'recharts';
import { 
  Calendar, Building2, Users, Tag, Share2, Download, LayoutTemplate, 
  Plus, X, Save, Settings, Trash2, LayoutDashboard, ArrowUpRight, ArrowDownRight, ArrowRight, Activity, DollarSign
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogTitle, DialogHeader } from '@/components/ui/dialog';

import { useAuth } from '@/lib/firebase/auth-context';
import { subscribeToLeads } from '@/lib/firebase/database';
import { subscribeToCampaigns, Campaign } from '@/lib/db/campaigns/api';
import { subscribeToProjectsData } from '@/lib/db/projects/api';
import { Deal } from '@/lib/db/types';

// --- Data Schemas ---
type WidgetType = 'kpi' | 'bar' | 'donut' | 'line' | 'funnel' | 'area';

interface WidgetConfig {
  metricId: string;
  colorTheme: string;
}

interface Widget {
  id: string;
  type: WidgetType;
  title: string;
  config: WidgetConfig;
}

interface GlobalFilters {
  dateRange: string;
  pipeline: string;
  owner: string;
  tag: string;
}

const AVAILABLE_METRICS = [
  { id: 'total_pipeline_value', type: 'kpi', title: 'Total Pipeline Value', description: 'Money in play right now' },
  { id: 'total_revenue', type: 'kpi', title: 'Total Revenue (Won Deals)', description: 'Actual outcome metric' },
  { id: 'win_rate', type: 'kpi', title: 'Win Rate', description: 'Team conversion efficiency' },
  { id: 'avg_deal_size', type: 'kpi', title: 'Average Deal Size', description: 'Forecast & deal quality' },
  { id: 'pipeline_by_stage', type: 'bar', title: 'Pipeline Value by Stage', description: 'Where money is stuck' },
  { id: 'revenue_by_owner', type: 'bar', title: 'Revenue by Owner (Leaderboard)', description: 'Sales team performance' },
  { id: 'leads_by_source', type: 'bar', title: 'Leads Generated by Source', description: 'Marketing channel performance' },
  { id: 'campaign_roi', type: 'bar', title: 'Campaign ROI', description: 'Budget vs Spent' },
  { id: 'revenue_growth', type: 'line', title: 'Revenue Growth Over Time', description: 'Is business growing' },
  { id: 'win_rate_trend', type: 'line', title: 'Win Rate Trend', description: 'Efficiency over time' },
  { id: 'lead_gen_trend', type: 'line', title: 'Lead Generation Trend', description: 'Top-of-funnel volume' },
  { id: 'deal_status_breakdown', type: 'donut', title: 'Deal Status Breakdown', description: 'Open vs Won vs Lost' },
  { id: 'lead_intent_dist', type: 'donut', title: 'Lead Intent Distribution', description: 'Lead priority scoring' },
  { id: 'campaign_channels', type: 'donut', title: 'Campaign Channel Allocation', description: 'Channel mix' },
  { id: 'sales_funnel', type: 'funnel', title: 'Sales Pipeline Conversion', description: 'Signature CRM chart' },
  { id: 'lead_lifecycle', type: 'funnel', title: 'Lead Lifecycle Funnel', description: 'Top-of-funnel health' },
  { id: 'cumulative_revenue', type: 'area', title: 'Cumulative Revenue YTD', description: 'Up and to the right visual' },
  { id: 'active_pipeline_vol', type: 'area', title: 'Active Pipeline Volume Over Time', description: 'Pipeline health' },
];

const METRICS_BY_TYPE = {
  'KPIs': AVAILABLE_METRICS.filter(m => m.type === 'kpi'),
  'Bar Charts': AVAILABLE_METRICS.filter(m => m.type === 'bar'),
  'Line Charts': AVAILABLE_METRICS.filter(m => m.type === 'line'),
  'Donut Charts': AVAILABLE_METRICS.filter(m => m.type === 'donut'),
  'Funnel Charts': AVAILABLE_METRICS.filter(m => m.type === 'funnel'),
  'Area Charts': AVAILABLE_METRICS.filter(m => m.type === 'area'),
};

// --- Mock Data specific to metrics ---
const MOCK_DATA: Record<string, any> = {
  total_pipeline_value: { value: '$1,245,000', change: '+12%', trend: 'up' },
  total_revenue: { value: '$450,000', change: '+8%', trend: 'up' },
  win_rate: { value: '34%', change: '-2%', trend: 'down' },
  avg_deal_size: { value: '$24,500', change: '+5%', trend: 'up' },
  
  pipeline_by_stage: [
    { name: 'Lead', value: 120000 }, { name: 'Qualified', value: 300000 }, 
    { name: 'Proposal', value: 450000 }, { name: 'Negotiation', value: 250000 }, { name: 'Won', value: 125000 }
  ],
  revenue_by_owner: [
    { name: 'Sarah', value: 150000 }, { name: 'John', value: 120000 }, 
    { name: 'Mike', value: 95000 }, { name: 'Emma', value: 85000 }
  ],
  leads_by_source: [
    { name: 'Organic', value: 450 }, { name: 'Paid Ads', value: 320 }, 
    { name: 'Referral', value: 150 }, { name: 'Social', value: 280 }
  ],
  campaign_roi: [
    { name: 'Q1 Launch', budget: 5000, spent: 4800 }, 
    { name: 'Summer Promo', budget: 10000, spent: 12500 },
    { name: 'Retargeting', budget: 3000, spent: 1500 }
  ],
  revenue_growth: [
    { name: 'Jan', value: 20000 }, { name: 'Feb', value: 35000 }, { name: 'Mar', value: 45000 },
    { name: 'Apr', value: 42000 }, { name: 'May', value: 65000 }, { name: 'Jun', value: 85000 }
  ],
  win_rate_trend: [
    { name: 'Jan', value: 28 }, { name: 'Feb', value: 30 }, { name: 'Mar', value: 29 },
    { name: 'Apr', value: 32 }, { name: 'May', value: 34 }, { name: 'Jun', value: 35 }
  ],
  lead_gen_trend: [
    { name: 'Week 1', value: 120 }, { name: 'Week 2', value: 150 }, 
    { name: 'Week 3', value: 130 }, { name: 'Week 4', value: 190 }
  ],
  deal_status_breakdown: [
    { name: 'Open', value: 60 }, { name: 'Won', value: 25 }, { name: 'Lost', value: 15 }
  ],
  lead_intent_dist: [
    { name: 'High', value: 25 }, { name: 'Medium', value: 45 }, { name: 'Low', value: 30 }
  ],
  campaign_channels: [
    { name: 'Email', value: 40 }, { name: 'Social', value: 30 }, { name: 'Paid Search', value: 20 }, { name: 'Events', value: 10 }
  ],
  sales_funnel: [
    { name: 'Total Deals', value: 500 }, { name: 'Qualified', value: 350 },
    { name: 'Proposals', value: 200 }, { name: 'Negotiation', value: 100 }, { name: 'Closed Won', value: 50 }
  ],
  lead_lifecycle: [
    { name: 'Raw Leads', value: 1000 }, { name: 'MQL', value: 600 },
    { name: 'SQL', value: 300 }, { name: 'Opportunities', value: 150 }
  ],
  cumulative_revenue: [
    { name: 'Jan', value: 20000 }, { name: 'Feb', value: 55000 }, { name: 'Mar', value: 100000 },
    { name: 'Apr', value: 142000 }, { name: 'May', value: 207000 }, { name: 'Jun', value: 292000 }
  ],
  active_pipeline_vol: [
    { name: 'Jan', value: 500000 }, { name: 'Feb', value: 550000 }, { name: 'Mar', value: 480000 },
    { name: 'Apr', value: 600000 }, { name: 'May', value: 750000 }, { name: 'Jun', value: 800000 }
  ],
};

const INITIAL_WIDGETS: Widget[] = [
  { id: 'w1', type: 'kpi', title: 'Total Pipeline Value', config: { metricId: 'total_pipeline_value', colorTheme: '#3b82f6' } },
  { id: 'w2', type: 'kpi', title: 'Total Revenue (Won Deals)', config: { metricId: 'total_revenue', colorTheme: '#10b981' } },
  { id: 'w3', type: 'kpi', title: 'Win Rate', config: { metricId: 'win_rate', colorTheme: '#8b5cf6' } },
  { id: 'w4', type: 'kpi', title: 'Average Deal Size', config: { metricId: 'avg_deal_size', colorTheme: '#f59e0b' } },
  { id: 'w5', type: 'funnel', title: 'Sales Pipeline Conversion', config: { metricId: 'sales_funnel', colorTheme: '#ec4899' } },
  { id: 'w6', type: 'bar', title: 'Pipeline Value by Stage', config: { metricId: 'pipeline_by_stage', colorTheme: '#8b5cf6' } },
  { id: 'w7', type: 'line', title: 'Revenue Growth Over Time', config: { metricId: 'revenue_growth', colorTheme: '#10b981' } },
];

const THEME_COLORS: Record<string, string[]> = {
  '#8b5cf6': ['#8b5cf6', '#a78bfa', '#c4b5fd', '#ddd6fe', '#ede9fe'],
  '#ec4899': ['#ec4899', '#f472b6', '#fbcfe8', '#fce7f3', '#fdf2f8'],
  '#3b82f6': ['#3b82f6', '#60a5fa', '#93c5fd', '#bfdbfe', '#eff6ff'],
  '#10b981': ['#10b981', '#34d399', '#6ee7b7', '#a7f3d0', '#ecfdf5'],
  '#f59e0b': ['#f59e0b', '#fbbf24', '#fcd34d', '#fde68a', '#fffbeb'],
};

// --- Components ---

const WidgetRenderer = ({ widget, data }: { widget: Widget, data: any }) => {
  const color = widget.config.colorTheme || '#8b5cf6';
  const palette = THEME_COLORS[color] || THEME_COLORS['#8b5cf6'];

  if (!data) return <div className="flex items-center justify-center h-full text-slate-400">No data</div>;

  switch (widget.type) {
    case 'kpi':
      return (
        <div className="flex flex-col h-full justify-center">
          <div className="flex items-end gap-3 mb-2">
            <span className="text-4xl font-black tracking-tighter text-slate-900 dark:text-white">{data.value}</span>
            <Badge className={`font-bold mb-1 ${data.trend === 'up' ? 'bg-emerald-50 text-emerald-700 hover:bg-emerald-50 border-emerald-200' : 'bg-rose-50 text-rose-700 hover:bg-rose-50 border-rose-200'}`}>
              {data.trend === 'up' ? <ArrowUpRight className="w-3 h-3 mr-0.5" /> : <ArrowDownRight className="w-3 h-3 mr-0.5" />} 
              {data.change}
            </Badge>
          </div>
          <span className="text-sm font-semibold text-slate-500">vs last period</span>
        </div>
      );
    case 'bar':
      const isMultiBar = widget.config.metricId === 'campaign_roi';
      return (
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b', fontWeight: 600 }} dy={10} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b', fontWeight: 600 }} />
            <Tooltip cursor={{ fill: '#f8fafc' }} contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px -2px rgba(0,0,0,0.1)' }} />
            {isMultiBar ? (
              <>
                <Legend iconType="circle" wrapperStyle={{ fontSize: 12, fontWeight: 600, paddingTop: 10 }} />
                <Bar dataKey="budget" name="Budget" fill="#cbd5e1" radius={[4, 4, 0, 0]} />
                <Bar dataKey="spent" name="Spent" fill={color} radius={[4, 4, 0, 0]} />
              </>
            ) : (
              <Bar dataKey="value" fill={color} radius={[4, 4, 0, 0]} />
            )}
          </BarChart>
        </ResponsiveContainer>
      );
    case 'line':
      return (
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b', fontWeight: 600 }} dy={10} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b', fontWeight: 600 }} />
            <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px -2px rgba(0,0,0,0.1)' }} />
            <Line type="monotone" dataKey="value" stroke={color} strokeWidth={3} dot={{ strokeWidth: 2, r: 4, fill: '#fff' }} activeDot={{ r: 6, fill: color, stroke: '#fff', strokeWidth: 2 }} />
          </LineChart>
        </ResponsiveContainer>
      );
    case 'area':
      return (
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <defs>
              <linearGradient id={`color-${widget.id}`} x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor={color} stopOpacity={0.3}/>
                <stop offset="95%" stopColor={color} stopOpacity={0}/>
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b', fontWeight: 600 }} dy={10} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b', fontWeight: 600 }} />
            <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px -2px rgba(0,0,0,0.1)' }} />
            <Area type="monotone" dataKey="value" stroke={color} strokeWidth={3} fillOpacity={1} fill={`url(#color-${widget.id})`} />
          </AreaChart>
        </ResponsiveContainer>
      );
    case 'donut':
      return (
        <ResponsiveContainer width="100%" height="100%">
          <PieChart>
            <Pie data={data} innerRadius={60} outerRadius={100} paddingAngle={2} dataKey="value" stroke="none">
              {data.map((entry: any, index: number) => (
                <Cell key={`cell-${index}`} fill={palette[index % palette.length]} />
              ))}
            </Pie>
            <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px -2px rgba(0,0,0,0.1)' }} />
            <Legend verticalAlign="bottom" height={36} iconType="circle" wrapperStyle={{ fontSize: 12, fontWeight: 600 }} />
          </PieChart>
        </ResponsiveContainer>
      );
    case 'funnel':
      const maxVal = Math.max(...data.map((d: any) => d.value));
      return (
        <div className="flex flex-col h-full justify-center gap-3">
          {data.map((step: any, i: number) => {
            const width = Math.max((step.value / maxVal) * 100, 10);
            return (
              <div key={i} className="flex flex-col items-center group w-full">
                <div className="w-full flex justify-between text-xs font-bold text-slate-500 mb-1 px-4">
                  <span>{step.name}</span>
                  <span>{step.value}</span>
                </div>
                <div 
                  className="h-8 rounded-full transition-all duration-500 flex items-center justify-center relative overflow-hidden"
                  style={{ width: `${width}%`, backgroundColor: palette[i % palette.length] }}
                >
                  <div className="absolute inset-0 bg-white/20 opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
                {i < data.length - 1 && (
                  <ArrowDownRight className="w-4 h-4 text-slate-300 mt-2" />
                )}
              </div>
            )
          })}
        </div>
      );
    default:
      return <div className="flex items-center justify-center h-full text-slate-400 font-bold">Unsupported Type</div>;
  }
};

export default function AnalyticsDashboard() {
  const [isClient, setIsClient] = useState(false);
  
  // Global State
  const [isEditMode, setIsEditMode] = useState(false);
  const [widgets, setWidgets] = useState<Widget[]>(INITIAL_WIDGETS);
  const [selectedWidgetId, setSelectedWidgetId] = useState<string | null>(null);
  
  const [globalFilters, setGlobalFilters] = useState<GlobalFilters>({
    dateRange: '30days',
    pipeline: 'all',
    owner: 'all',
    tag: 'all'
  });

  const { user } = useAuth();
  const [deals, setDeals] = useState<Deal[]>([]);
  const [members, setMembers] = useState<any[]>([]);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);

  useEffect(() => {
    if (!user?.company_id) return;
    
    const unsubDeals = subscribeToLeads(user.company_id, setDeals);
    const unsubMembers = subscribeToProjectsData(user.company_id, (data) => setMembers(data.members || []));
    const unsubCampaigns = subscribeToCampaigns(user.company_id, setCampaigns);
    
    return () => {
      unsubDeals();
      unsubMembers();
      unsubCampaigns();
    };
  }, [user]);

  const dashboardData = useMemo(() => {
    // Remove mock data fallback: calculate zeroed/empty structures instead if no deals exist.
    const openDeals = deals.filter(d => d.status !== 'won' && d.status !== 'lost');
    const wonDeals = deals.filter(d => d.status === 'won');
    const lostDeals = deals.filter(d => d.status === 'lost');
    const resolvedDeals = wonDeals.length + lostDeals.length;

    const totalPipeline = openDeals.reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0);
    const totalRevenue = wonDeals.reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0);
    const winRate = resolvedDeals > 0 ? Math.round((wonDeals.length / resolvedDeals) * 100) : 0;
    const avgDealSize = wonDeals.length > 0 ? Math.round(totalRevenue / wonDeals.length) : 0;

    const pipelineByStage = [
      { name: 'Lead', value: openDeals.filter(d => d.status === 'new' || d.status === 'contacted').reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0) },
      { name: 'Qualified', value: openDeals.filter(d => d.status === 'qualified').reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0) },
      { name: 'Proposal', value: openDeals.filter(d => d.status === 'proposal').reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0) },
      { name: 'Negotiation', value: openDeals.filter(d => d.status === 'negotiation').reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0) }
    ];

    const revenueByOwnerMap: Record<string, number> = {};
    wonDeals.forEach(d => {
      const ownerId = (d as any).owner_id || (d as any).assigned_to;
      if (ownerId) {
        revenueByOwnerMap[ownerId] = (revenueByOwnerMap[ownerId] || 0) + ((d as any).estimated_value || 0);
      }
    });
    
    const revenueByOwner = Object.entries(revenueByOwnerMap).map(([ownerId, value]) => {
      const member = members.find(m => m.id === ownerId);
      return { name: member ? member.name.split(' ')[0] : 'Unknown', value };
    }).sort((a, b) => b.value - a.value);

    const salesFunnel = [
      { name: 'Total Deals', value: deals.length },
      { name: 'Qualified', value: deals.filter(d => d.status === 'qualified' || d.status === 'proposal' || d.status === 'negotiation' || d.status === 'won').length },
      { name: 'Proposals', value: deals.filter(d => d.status === 'proposal' || d.status === 'negotiation' || d.status === 'won').length },
      { name: 'Negotiation', value: deals.filter(d => d.status === 'negotiation' || d.status === 'won').length },
      { name: 'Closed Won', value: wonDeals.length }
    ];

    const dealStatusDist = [
      { name: 'Open', value: openDeals.length },
      { name: 'Won', value: wonDeals.length },
      { name: 'Lost', value: lostDeals.length }
    ];

    const campaignRoi = campaigns.map(c => ({
      name: c.name.length > 15 ? c.name.substring(0, 15) + '...' : c.name,
      budget: c.budget || 0,
      spent: c.spent || 0
    }));

    // Generate basic historical timeseries data (grouping by month)
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const currentMonth = new Date().getMonth();
    const last6Months = Array.from({ length: 6 }).map((_, i) => {
      const d = new Date();
      d.setMonth(currentMonth - (5 - i));
      return { monthIndex: d.getMonth(), year: d.getFullYear(), name: months[d.getMonth()] };
    });

    const revenueGrowth = last6Months.map(m => {
      const revInMonth = wonDeals.filter(d => {
        const closedAt = (d as any).closed_at || d.updated_at;
        if (!closedAt) return false;
        const closedDate = new Date(closedAt);
        return closedDate.getMonth() === m.monthIndex && closedDate.getFullYear() === m.year;
      }).reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0);
      return { name: m.name, value: revInMonth };
    });
    
    // Cumulative revenue growth logic
    let runningTotal = 0;
    const cumulativeRevenueGrowth = revenueGrowth.map(item => {
      runningTotal += item.value;
      return { name: item.name, value: runningTotal };
    });

    const activePipelineVolume = last6Months.map(m => {
      // Find open deals that were created on or before this month
      const vol = deals.filter(d => {
        if (!d.created_at || d.status === 'won' || d.status === 'lost') return false;
        const createdDate = new Date(d.created_at);
        return (createdDate.getFullYear() < m.year) || (createdDate.getFullYear() === m.year && createdDate.getMonth() <= m.monthIndex);
      }).reduce((acc, d) => acc + ((d as any).estimated_value || 0), 0);
      return { name: m.name, value: vol };
    });

    const winRateTrend = last6Months.map(m => {
      const resolvedInMonth = deals.filter(d => {
        const closedAt = (d as any).closed_at || d.updated_at;
        if (!closedAt || (d.status !== 'won' && d.status !== 'lost')) return false;
        const closedDate = new Date(closedAt);
        return closedDate.getMonth() === m.monthIndex && closedDate.getFullYear() === m.year;
      });
      const wonInMonth = resolvedInMonth.filter(d => d.status === 'won');
      const wr = resolvedInMonth.length > 0 ? Math.round((wonInMonth.length / resolvedInMonth.length) * 100) : 0;
      return { name: m.name, value: wr };
    });

    return {
      total_pipeline_value: { value: `$${totalPipeline.toLocaleString()}`, change: '+0%', trend: 'up' },
      total_revenue: { value: `$${totalRevenue.toLocaleString()}`, change: '+0%', trend: 'up' },
      win_rate: { value: `${winRate}%`, change: '+0%', trend: 'up' },
      avg_deal_size: { value: `$${avgDealSize.toLocaleString()}`, change: '+0%', trend: 'up' },
      pipeline_by_stage: pipelineByStage,
      revenue_by_owner: revenueByOwner,
      sales_funnel: salesFunnel,
      deal_status_breakdown: dealStatusDist,
      campaign_roi: campaignRoi,
      revenue_growth: cumulativeRevenueGrowth,
      active_pipeline_volume: activePipelineVolume,
      win_rate_trend: winRateTrend
    };
  }, [deals, members, campaigns]);

  // Modals
  const [isAddOpen, setIsAddOpen] = useState(false);

  useEffect(() => setIsClient(true), []);

  const handleDragEnd = (result: DropResult) => {
    if (!result.destination || !isEditMode) return;
    
    const items = Array.from(widgets);
    const [reorderedItem] = items.splice(result.source.index, 1);
    items.splice(result.destination.index, 0, reorderedItem);
    
    setWidgets(items);
  };

  const removeWidget = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setWidgets(prev => prev.filter(w => w.id !== id));
    if (selectedWidgetId === id) setSelectedWidgetId(null);
  };

  const addWidget = (metric: typeof AVAILABLE_METRICS[0]) => {
    const newWidget: Widget = {
      id: `w_${Date.now()}`,
      type: metric.type as WidgetType,
      title: metric.title,
      config: {
        metricId: metric.id,
        colorTheme: '#8b5cf6',
      }
    };
    setWidgets([...widgets, newWidget]);
    setIsAddOpen(false);
  };

  const getWidgetStyle = (type: WidgetType) => {
    switch (type) {
      case 'kpi': return { width: 'calc(25% - 15px)', minWidth: '200px', height: '160px', flexGrow: 1 };
      case 'donut': return { width: '380px', height: '380px', flexGrow: 1 };
      case 'funnel': return { width: 'calc(33% - 15px)', minWidth: '340px', height: '460px', flexGrow: 1 };
      default: return { width: 'calc(50% - 10px)', minWidth: '400px', height: '380px', flexGrow: 1 };
    }
  };

  if (!isClient) return null;

  return (
    <div className="flex flex-col h-[calc(100vh-100px)] min-h-0 bg-[#f8fafc] dark:bg-background">
      
      {/* Top Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 bg-white dark:bg-card border-b border-slate-200 dark:border-slate-800 shrink-0 z-20 shadow-sm relative">
        <div className="flex items-center gap-4">
          <div>
            <h1 className="text-2xl font-black tracking-tight text-[#1e1a4f] dark:text-foreground font-sans" style={{ fontFamily: "'Outfit', sans-serif" }}>Analytics Dashboard</h1>
            <p className="text-sm text-slate-500 dark:text-slate-400 font-medium mt-1">Real-time performance metrics across all client accounts.</p>
          </div>
          {isEditMode && <Badge className="bg-blue-50 text-blue-700 border-blue-200 uppercase font-black tracking-widest text-[10px] h-6 px-3">Edit Mode</Badge>}
        </div>
        
        <div className="flex items-center gap-3">
          {!isEditMode ? (
            <>
              <Button variant="ghost" className="font-bold text-slate-600 hover:text-slate-900 rounded-xl"><Share2 className="w-4 h-4 mr-2" /> Share</Button>
              <Button variant="ghost" className="font-bold text-slate-600 hover:text-slate-900 rounded-xl"><Download className="w-4 h-4 mr-2" /> Export</Button>
              <Button className="bg-[#1e1a4f] hover:bg-[#2d2770] text-white rounded-xl shadow-md font-bold px-5" onClick={() => setIsEditMode(true)}>
                <LayoutTemplate className="w-4 h-4 mr-2" /> Edit Layout
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" className="border-blue-200 text-blue-700 hover:bg-blue-50 font-bold rounded-xl shadow-sm bg-white" onClick={() => setIsAddOpen(true)}>
                <Plus className="w-4 h-4 mr-2" /> Add Component
              </Button>
              <div className="w-px h-8 bg-slate-200 mx-1" />
              <Button variant="ghost" className="font-bold text-slate-600 hover:text-slate-900 rounded-xl" onClick={() => { setIsEditMode(false); setSelectedWidgetId(null); }}>
                Cancel
              </Button>
              <Button className="bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl shadow-md font-bold px-5" onClick={() => { setIsEditMode(false); setSelectedWidgetId(null); }}>
                <Save className="w-4 h-4 mr-2" /> Save Changes
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Global Filters Row */}
      <div className="bg-white dark:bg-card border-b border-slate-200 dark:border-slate-800 p-3 px-5 flex flex-wrap items-center gap-4 shrink-0 z-10">
        <span className="text-xs font-black uppercase text-slate-400 dark:text-slate-500 tracking-widest">Filters:</span>
        <Select value={globalFilters.dateRange} onValueChange={v => setGlobalFilters(p => ({...p, dateRange: v}))}>
          <SelectTrigger className="w-[180px] h-9 bg-slate-50 dark:bg-slate-800 border-transparent shadow-none font-bold text-sm hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors rounded-lg"><Calendar className="w-4 h-4 mr-2 text-slate-400 dark:text-slate-500" /><SelectValue /></SelectTrigger>
          <SelectContent><SelectItem value="7days">Last 7 Days</SelectItem><SelectItem value="30days">Last 30 Days</SelectItem><SelectItem value="thisYear">This Year</SelectItem></SelectContent>
        </Select>
        <Select value={globalFilters.pipeline} onValueChange={v => setGlobalFilters(p => ({...p, pipeline: v}))}>
          <SelectTrigger className="w-[180px] h-9 bg-slate-50 dark:bg-slate-800 border-transparent shadow-none font-bold text-sm hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors rounded-lg"><Building2 className="w-4 h-4 mr-2 text-slate-400 dark:text-slate-500" /><SelectValue /></SelectTrigger>
          <SelectContent><SelectItem value="all">All Pipelines</SelectItem><SelectItem value="sales">Sales Pipeline</SelectItem><SelectItem value="partners">Partner Pipeline</SelectItem></SelectContent>
        </Select>
        <Select value={globalFilters.owner} onValueChange={v => setGlobalFilters(p => ({...p, owner: v}))}>
          <SelectTrigger className="w-[180px] h-9 bg-slate-50 dark:bg-slate-800 border-transparent shadow-none font-bold text-sm hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors rounded-lg"><Users className="w-4 h-4 mr-2 text-slate-400 dark:text-slate-500" /><SelectValue /></SelectTrigger>
          <SelectContent><SelectItem value="all">All Owners</SelectItem><SelectItem value="me">Assigned to Me</SelectItem></SelectContent>
        </Select>
      </div>

      <div className="flex-1 flex overflow-hidden min-h-0 relative">
        
        {/* The Canvas Grid */}
        <div className="flex-1 overflow-y-auto p-6 flex flex-col">
          {widgets.length === 0 ? (
            <div className="flex-1 flex flex-col items-center justify-center text-center">
              <div className="w-20 h-20 rounded-full border-2 border-dashed border-slate-300 dark:border-slate-700 flex items-center justify-center mb-6">
                <LayoutDashboard className="w-8 h-8 text-slate-400 dark:text-slate-500" />
              </div>
              <h3 className="text-xl font-black text-slate-900 dark:text-slate-100 tracking-tight">Your Dashboard is Empty</h3>
              <p className="text-slate-500 dark:text-slate-400 font-medium mt-2 mb-6 max-w-sm">Start building your custom view by adding components to the grid.</p>
              {!isEditMode && <Button onClick={() => setIsEditMode(true)} className="rounded-xl font-bold bg-[#1e1a4f] text-white">Edit Layout</Button>}
            </div>
          ) : (
            <DragDropContext onDragEnd={handleDragEnd}>
              <Droppable droppableId="dashboard" direction="horizontal" isDropDisabled={!isEditMode}>
                {(provided, snapshot) => (
                  <div 
                    {...provided.droppableProps} 
                    ref={provided.innerRef}
                    className="flex flex-wrap gap-5 w-full items-start"
                  >
                    {widgets.map((w, index) => (
                      <Draggable key={w.id} draggableId={w.id} index={index} isDragDisabled={!isEditMode}>
                        {(provided, snapshot) => {
                          const style = getWidgetStyle(w.type);
                          const isSelected = selectedWidgetId === w.id;
                          
                          return (
                            <div
                              ref={provided.innerRef}
                              {...provided.draggableProps}
                              {...provided.dragHandleProps}
                              style={{ 
                                ...provided.draggableProps.style,
                                ...style,
                                opacity: snapshot.isDragging ? 0.8 : 1,
                                zIndex: snapshot.isDragging ? 50 : 1,
                              }}
                              className={`relative group bg-white dark:bg-card rounded-[16px] border shadow-sm flex flex-col transition-all duration-200
                                ${isEditMode ? 'cursor-grab active:cursor-grabbing hover:border-slate-300 dark:hover:border-slate-600' : ''}
                                ${isSelected && isEditMode ? 'ring-2 ring-blue-500 border-blue-500 shadow-md' : 'border-slate-200 dark:border-slate-800'}
                              `}
                              onClick={() => { if(isEditMode) setSelectedWidgetId(w.id); }}
                            >
                              <div className="flex items-center justify-between p-4 px-5">
                                <h3 className="font-bold text-slate-900 dark:text-white tracking-tight">{w.title}</h3>
                                {isEditMode && (
                                  <div className="flex gap-2">
                                    <Button variant="ghost" size="icon" className="w-8 h-8 rounded-lg text-slate-400 hover:text-red-500 hover:bg-red-50" onClick={() => setWidgets(widgets.filter(x => x.id !== w.id))}><Trash2 className="w-4 h-4" /></Button>
                                    <Button variant="ghost" size="icon" className="w-8 h-8 rounded-lg text-slate-400 hover:text-blue-500 hover:bg-blue-50" onClick={() => setSelectedWidgetId(w.id)}><Settings className="w-4 h-4" /></Button>
                                  </div>
                                )}
                              </div>
                              <div className="flex-1 p-5 pt-0 min-h-0 relative">
                                <WidgetRenderer widget={w} data={dashboardData[w.config.metricId]} />
                                {isEditMode && <div className="absolute inset-0 bg-transparent" />}
                              </div>
                            </div>
                          )
                        }}
                      </Draggable>
                    ))}
                    {provided.placeholder}
                  </div>
                )}
              </Droppable>
            </DragDropContext>
          )}
        </div>

        {/* Configurator Panel */}
        {isEditMode && selectedWidgetId && (
          <div className="w-80 border-l border-slate-200 dark:border-slate-800 bg-white dark:bg-card shadow-[-8px_0_24px_-12px_rgba(0,0,0,0.1)] z-20 flex flex-col shrink-0 animate-in slide-in-from-right-4 duration-300">
            <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
              <h3 className="font-black text-slate-900 dark:text-slate-100 tracking-tight">Widget Settings</h3>
              <button className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300" onClick={() => setSelectedWidgetId(null)}><X className="w-4 h-4" /></button>
            </div>
            
            <div className="p-5 overflow-y-auto flex-1 space-y-6">
              <div className="space-y-2">
                <label className="text-[11px] font-black uppercase text-slate-500 dark:text-slate-400 tracking-wider">Widget Title</label>
                <Input 
                  value={widgets.find(w => w.id === selectedWidgetId)?.title || ''} 
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setWidgets(prev => prev.map(w => w.id === selectedWidgetId ? {...w, title: e.target.value} : w))}
                  className="h-10 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 font-bold rounded-xl focus-visible:ring-blue-500"
                />
              </div>

              <div className="space-y-2">
                <label className="text-[11px] font-black uppercase text-slate-500 tracking-wider">Color Theme</label>
                <div className="flex items-center gap-3 flex-wrap">
                  {Object.keys(THEME_COLORS).map(c => (
                    <button
                      key={c}
                      className={`w-8 h-8 rounded-full ring-2 ring-offset-2 transition-all ${widgets.find(w => w.id === selectedWidgetId)?.config.colorTheme === c ? 'ring-blue-500' : 'ring-transparent hover:ring-slate-300'}`}
                      style={{ backgroundColor: c }}
                      onClick={() => setWidgets(prev => prev.map(w => w.id === selectedWidgetId ? {...w, config: {...w.config, colorTheme: c}} : w))}
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Dynamic Add Component Modal */}
      <Dialog open={isAddOpen} onOpenChange={setIsAddOpen}>
        <DialogContent className="sm:max-w-[800px] max-h-[80vh] overflow-y-auto p-0 bg-[#f8fafc] dark:bg-card border-0 shadow-2xl rounded-[1.5rem]">
          <DialogHeader className="p-8 pb-4 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 sticky top-0 z-10">
            <DialogTitle className="text-2xl font-black text-[#1e1a4f] dark:text-foreground tracking-tight">Add Component</DialogTitle>
            <p className="text-sm text-slate-500 font-medium">Select a metric to add to your dashboard grid.</p>
          </DialogHeader>
          
          <div className="p-8 pt-6 space-y-10">
            {Object.entries(METRICS_BY_TYPE).map(([category, metrics]) => (
              <div key={category} className="space-y-4">
                <h4 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                  {category} <Badge className="bg-slate-200 text-slate-700 hover:bg-slate-200 border-none">{metrics.length}</Badge>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {metrics.map(metric => (
                    <div 
                      key={metric.id} 
                      onClick={() => addWidget(metric)}
                      className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 flex flex-col gap-2 cursor-pointer hover:border-blue-500 hover:shadow-md transition-all group"
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-bold text-sm text-slate-900 dark:text-slate-100">{metric.title}</span>
                        <Plus className="w-4 h-4 text-slate-300 group-hover:text-blue-500 transition-colors" />
                      </div>
                      <span className="text-xs font-medium text-slate-500 leading-relaxed">{metric.description}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
