'use client';

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { DragDropContext, Droppable, Draggable, DropResult } from '@hello-pangea/dnd';
import {
  BarChart, Bar, LineChart, Line, AreaChart, Area, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend
} from 'recharts';
import {
  Calendar, Building2, Users, Share2, Download, LayoutTemplate,
  Plus, X, Save, Settings, Trash2, LayoutDashboard, ArrowUpRight, ArrowDownRight, ArrowRight, TrendingUp
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogTitle, DialogHeader } from '@/components/ui/dialog';
import { KpiCard } from '@/components/dashboard/kpi-card';

import { useAuth } from '@/lib/firebase/auth-context';
import { subscribeToLeads } from '@/lib/firebase/database';
import { subscribeToCampaigns, Campaign } from '@/lib/db/campaigns/api';
import { subscribeToProjectsData } from '@/lib/db/projects/api';
import { subscribeToDashboardSettings, saveDashboardSettings, DashboardSettings, WidgetLayout } from '@/lib/db/dashboard/api';
import { Lead } from '@/lib/db/types';

type WidgetType = 'kpi' | 'bar' | 'donut' | 'line' | 'funnel' | 'area';

interface Widget {
  id: string;
  type: WidgetType;
  title: string;
  config: {
    metricId: string;
    colorTheme: string;
  };
}

interface GlobalFilters {
  dateRange: string;
  pipeline: string;
  owner: string;
  tag: string;
}

const AVAILABLE_METRICS = [
  { id: 'total_pipeline_value', type: 'kpi', title: 'Total Pipeline Value', description: 'Money in play right now' },
  { id: 'total_revenue', type: 'kpi', title: 'Total Revenue (Won Deals)', description: 'Actual outcome metric' },
  { id: 'win_rate', type: 'kpi', title: 'Win Rate', description: 'Team conversion efficiency' },
  { id: 'avg_deal_size', type: 'kpi', title: 'Average Deal Size', description: 'Forecast & deal quality' },
  { id: 'pipeline_by_stage', type: 'bar', title: 'Pipeline Value by Stage', description: 'Where money is stuck' },
  { id: 'revenue_by_owner', type: 'bar', title: 'Revenue by Owner (Leaderboard)', description: 'Sales team performance' },
  { id: 'leads_by_source', type: 'bar', title: 'Leads Generated by Source', description: 'Marketing channel performance' },
  { id: 'campaign_roi', type: 'bar', title: 'Campaign ROI', description: 'Budget vs Spent' },
  { id: 'revenue_growth', type: 'line', title: 'Revenue Growth Over Time', description: 'Is business growing' },
  { id: 'win_rate_trend', type: 'line', title: 'Win Rate Trend', description: 'Efficiency over time' },
  { id: 'lead_gen_trend', type: 'line', title: 'Lead Generation Trend', description: 'Top-of-funnel volume' },
  { id: 'deal_status_breakdown', type: 'donut', title: 'Deal Status Breakdown', description: 'Open vs Won vs Lost' },
  { id: 'lead_intent_dist', type: 'donut', title: 'Lead Intent Distribution', description: 'Lead priority scoring' },
  { id: 'campaign_channels', type: 'donut', title: 'Campaign Channel Allocation', description: 'Channel mix' },
  { id: 'sales_funnel', type: 'funnel', title: 'Sales Pipeline Conversion', description: 'Signature CRM chart' },
  { id: 'lead_lifecycle', type: 'funnel', title: 'Lead Lifecycle Funnel', description: 'Top-of-funnel health' },
  { id: 'cumulative_revenue', type: 'area', title: 'Cumulative Revenue YTD', description: 'Up and to the right visual' },
  { id: 'active_pipeline_vol', type: 'area', title: 'Active Pipeline Volume Over Time', description: 'Pipeline health' },
];

const METRICS_BY_TYPE = {
  'KPIs': AVAILABLE_METRICS.filter(m => m.type === 'kpi'),
  'Bar Charts': AVAILABLE_METRICS.filter(m => m.type === 'bar'),
  'Line Charts': AVAILABLE_METRICS.filter(m => m.type === 'line'),
  'Donut Charts': AVAILABLE_METRICS.filter(m => m.type === 'donut'),
  'Funnel Charts': AVAILABLE_METRICS.filter(m => m.type === 'funnel'),
  'Area Charts': AVAILABLE_METRICS.filter(m => m.type === 'area'),
};

const THEME_COLORS: Record<string, string[]> = {
  '#8b5cf6': ['#8b5cf6', '#a78bfa', '#c4b5fd', '#ddd6fe', '#ede9fe'],
  '#ec4899': ['#ec4899', '#f472b6', '#fbcfe8', '#fce7f3', '#fdf2f8'],
  '#3b82f6': ['#3b82f6', '#60a5fa', '#93c5fd', '#bfdbfe', '#eff6ff'],
  '#10b981': ['#10b981', '#34d399', '#6ee7b7', '#a7f3d0', '#ecfdf5'],
  '#f59e0b': ['#f59e0b', '#fbbf24', '#fcd34d', '#fde68a', '#fffbeb'],
};

const DEFAULT_WIDGETS: Widget[] = [
  { id: 'w1', type: 'kpi', title: 'Total Pipeline Value', config: { metricId: 'total_pipeline_value', colorTheme: '#3b82f6' } },
  { id: 'w2', type: 'kpi', title: 'Total Revenue (Won Deals)', config: { metricId: 'total_revenue', colorTheme: '#10b981' } },
  { id: 'w3', type: 'kpi', title: 'Win Rate', config: { metricId: 'win_rate', colorTheme: '#8b5cf6' } },
  { id: 'w4', type: 'kpi', title: 'Average Deal Size', config: { metricId: 'avg_deal_size', colorTheme: '#f59e0b' } },
  { id: 'w5', type: 'funnel', title: 'Sales Pipeline Conversion', config: { metricId: 'sales_funnel', colorTheme: '#ec4899' } },
  { id: 'w6', type: 'bar', title: 'Pipeline Value by Stage', config: { metricId: 'pipeline_by_stage', colorTheme: '#8b5cf6' } },
  { id: 'w7', type: 'line', title: 'Revenue Growth Over Time', config: { metricId: 'revenue_growth', colorTheme: '#10b981' } },
];

const WidgetRenderer = ({ widget, data }: { widget: Widget; data: any }) => {
  const color = widget.config.colorTheme || '#8b5cf6';
  const palette = THEME_COLORS[color] || THEME_COLORS['#8b5cf6'];

  if (!data) return <div className="flex items-center justify-center h-full text-muted-foreground">No data</div>;

  switch (widget.type) {
    case 'kpi':
      return (
        <div className="flex flex-col h-full justify-center">
          <div className="flex items-end gap-3 mb-2">
            <span className="text-4xl font-bold tracking-tight">{data.value}</span>
            <Badge className={data.trend === 'up' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-400' : 'bg-red-50 text-red-700 dark:bg-red-950 dark:text-red-400'}>
              {data.trend === 'up' ? <ArrowUpRight className="w-3 h-3 mr-0.5" /> : <ArrowDownRight className="w-3 h-3 mr-0.5" />}
              {data.change}
            </Badge>
          </div>
          <span className="text-sm text-muted-foreground">vs last period</span>
        </div>
      );
    case 'bar':
      const isMultiBar = widget.config.metricId === 'campaign_roi';
      return (
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} className="stroke-border" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} dy={10} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
            <Tooltip cursor={{ fill: 'hsl(var(--muted))' }} contentStyle={{ borderRadius: '8px', border: '1px solid hsl(var(--border))', backgroundColor: 'hsl(var(--card))' }} />
            {isMultiBar ? (
              <>
                <Legend iconType="circle" wrapperStyle={{ fontSize: 12, paddingTop: 10 }} />
                <Bar dataKey="budget" name="Budget" fill="hsl(var(--muted))" radius={[4, 4, 0, 0]} />
                <Bar dataKey="spent" name="Spent" fill={color} radius={[4, 4, 0, 0]} />
              </>
            ) : (
              <Bar dataKey="value" fill={color} radius={[4, 4, 0, 0]} />
            )}
          </BarChart>
        </ResponsiveContainer>
      );
    case 'line':
      return (
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} className="stroke-border" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} dy={10} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
            <Tooltip contentStyle={{ borderRadius: '8px', border: '1px solid hsl(var(--border))', backgroundColor: 'hsl(var(--card))' }} />
            <Line type="monotone" dataKey="value" stroke={color} strokeWidth={2} dot={{ strokeWidth: 2, r: 4, fill: 'hsl(var(--background))' }} activeDot={{ r: 6, fill: color, stroke: 'hsl(var(--background))', strokeWidth: 2 }} />
          </LineChart>
        </ResponsiveContainer>
      );
    case 'area':
      return (
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <defs>
              <linearGradient id={`color-${widget.id}`} x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor={color} stopOpacity={0.3} />
                <stop offset="95%" stopColor={color} stopOpacity={0} />
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="3 3" vertical={false} className="stroke-border" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} dy={10} />
            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
            <Tooltip contentStyle={{ borderRadius: '8px', border: '1px solid hsl(var(--border))', backgroundColor: 'hsl(var(--card))' }} />
            <Area type="monotone" dataKey="value" stroke={color} strokeWidth={2} fillOpacity={1} fill={`url(#color-${widget.id})`} />
          </AreaChart>
        </ResponsiveContainer>
      );
    case 'donut':
      return (
        <ResponsiveContainer width="100%" height="100%">
          <PieChart>
            <Pie data={data} innerRadius={60} outerRadius={100} paddingAngle={2} dataKey="value" stroke="none">
              {data.map((entry: any, index: number) => (
                <Cell key={`cell-${index}`} fill={palette[index % palette.length]} />
              ))}
            </Pie>
            <Tooltip contentStyle={{ borderRadius: '8px', border: '1px solid hsl(var(--border))', backgroundColor: 'hsl(var(--card))' }} />
            <Legend verticalAlign="bottom" height={36} iconType="circle" wrapperStyle={{ fontSize: 12 }} />
          </PieChart>
        </ResponsiveContainer>
      );
    case 'funnel':
      const maxVal = Math.max(...data.map((d: any) => d.value));
      return (
        <div className="flex flex-col h-full justify-center gap-1">
          {data.map((step: any, i: number) => {
            const width = maxVal > 0 ? Math.max((step.value / maxVal) * 100, 10) : 100;
            return (
              <div key={i} className="flex flex-col items-center group w-full">
                <div className="w-full flex justify-between text-xs font-medium text-muted-foreground mb-1 px-4">
                  <span>{step.name}</span>
                  <span>{step.value}</span>
                </div>
                <div
                  className="h-8 rounded-lg transition-all duration-500 flex items-center justify-center relative overflow-hidden"
                  style={{ width: `${width}%`, backgroundColor: palette[i % palette.length] }}
                >
                  <div className="absolute inset-0 bg-white/20 opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
                {i < data.length - 1 && (
                  <div className="flex flex-col items-center my-1">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="text-muted-foreground">
                      <path d="M8 3v8M4.5 7.5L8 11l3.5-3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      );
    default:
      return <div className="flex items-center justify-center h-full text-muted-foreground">Unsupported Type</div>;
  }
};

export default function AnalyticsDashboard() {
  const [isClient, setIsClient] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [widgets, setWidgets] = useState<Widget[]>(DEFAULT_WIDGETS);
  const [selectedWidgetId, setSelectedWidgetId] = useState<string | null>(null);
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [globalFilters, setGlobalFilters] = useState<GlobalFilters>({
    dateRange: '30days',
    pipeline: 'all',
    owner: 'all',
    tag: 'all'
  });
  const [settingsLoaded, setSettingsLoaded] = useState(false);

  const { user } = useAuth();
  const [deals, setDeals] = useState<Lead[]>([]);
  const [members, setMembers] = useState<any[]>([]);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);

  useEffect(() => {
    if (!user?.company_id) return;
    const unsubDeals = subscribeToLeads(user.company_id, setDeals);
    const unsubMembers = subscribeToProjectsData(user.company_id, (data) => setMembers(data.members || []));
    const unsubCampaigns = subscribeToCampaigns(user.company_id, setCampaigns);
    return () => { unsubDeals(); unsubMembers(); unsubCampaigns(); };
  }, [user]);

  // Load dashboard settings from Firebase
  useEffect(() => {
    if (!user?.company_id || settingsLoaded) return;
    const unsub = subscribeToDashboardSettings(user.company_id, (settings) => {
      if (settings) {
        if (settings.widgets && settings.widgets.length > 0) {
          setWidgets(settings.widgets as Widget[]);
        }
        if (settings.globalFilters) {
          setGlobalFilters(settings.globalFilters);
        }
      }
      setSettingsLoaded(true);
    });
    return () => unsub();
  }, [user?.company_id, settingsLoaded]);

  // Persist dashboard settings to Firebase when widgets or filters change
  const persistSettings = useCallback(async () => {
    if (!user?.company_id || !settingsLoaded) return;
    try {
      await saveDashboardSettings(user.company_id, {
        widgets: widgets as WidgetLayout[],
        globalFilters,
      });
    } catch (e) {
      console.error('Failed to save dashboard settings:', e);
    }
  }, [user?.company_id, widgets, globalFilters, settingsLoaded]);

  // Auto-save when exiting edit mode
  useEffect(() => {
    if (!isEditMode && settingsLoaded) {
      persistSettings();
    }
  }, [isEditMode]);

  // Filter deals based on global filters
  const filteredDeals = useMemo(() => {
    let result = deals;

    if (globalFilters.owner !== 'all') {
      result = result.filter(d => d.owner_id === user?.id);
    }

    if (globalFilters.pipeline !== 'all') {
      // Pipeline filtering would need pipeline_id on deals
      // For now, show all if a specific pipeline is selected
    }

    return result;
  }, [deals, globalFilters, user?.id]);

  const dashboardData = useMemo(() => {
    const openDeals = filteredDeals.filter(d => d.status !== 'won' && d.status !== 'lost');
    const wonDeals = filteredDeals.filter(d => d.status === 'won');
    const lostDeals = filteredDeals.filter(d => d.status === 'lost');
    const resolvedDeals = wonDeals.length + lostDeals.length;

    const totalPipeline = openDeals.reduce((acc, d) => acc + (d.estimated_value || 0), 0);
    const totalRevenue = wonDeals.reduce((acc, d) => acc + (d.estimated_value || 0), 0);
    const winRate = resolvedDeals > 0 ? Math.round((wonDeals.length / resolvedDeals) * 100) : 0;
    const avgDealSize = wonDeals.length > 0 ? Math.round(totalRevenue / wonDeals.length) : 0;

    // Compute change values from previous period
    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();
    const prevMonth = currentMonth === 0 ? 11 : currentMonth - 1;
    const prevYear = currentMonth === 0 ? currentYear - 1 : currentYear;

    const wonThisMonth = wonDeals.filter(d => {
      const closedAt = d.updated_at;
      if (!closedAt) return false;
      const date = new Date(closedAt);
      return date.getMonth() === currentMonth && date.getFullYear() === currentYear;
    });
    const wonPrevMonth = wonDeals.filter(d => {
      const closedAt = d.updated_at;
      if (!closedAt) return false;
      const date = new Date(closedAt);
      return date.getMonth() === prevMonth && date.getFullYear() === prevYear;
    });

    const revenueThisMonth = wonThisMonth.reduce((acc, d) => acc + (d.estimated_value || 0), 0);
    const revenuePrevMonth = wonPrevMonth.reduce((acc, d) => acc + (d.estimated_value || 0), 0);

    const resolvedThisMonth = wonThisMonth.length + lostDeals.filter(d => {
      const closedAt = d.updated_at;
      if (!closedAt) return false;
      const date = new Date(closedAt);
      return date.getMonth() === currentMonth && date.getFullYear() === currentYear;
    }).length;
    const resolvedPrevMonth = wonPrevMonth.length + lostDeals.filter(d => {
      const closedAt = d.updated_at;
      if (!closedAt) return false;
      const date = new Date(closedAt);
      return date.getMonth() === prevMonth && date.getFullYear() === prevYear;
    }).length;

    const winRateThisMonth = resolvedThisMonth > 0 ? Math.round((wonThisMonth.length / resolvedThisMonth) * 100) : 0;
    const winRatePrevMonth = resolvedPrevMonth > 0 ? Math.round((wonPrevMonth.length / resolvedPrevMonth) * 100) : 0;

    const formatChange = (current: number, previous: number) => {
      if (previous === 0) return current > 0 ? '+100%' : '+0%';
      const change = ((current - previous) / previous) * 100;
      return `${change >= 0 ? '+' : ''}${Math.round(change)}%`;
    };

    const revenueChange = formatChange(revenueThisMonth, revenuePrevMonth);
    const winRateChange = formatChange(winRateThisMonth, winRatePrevMonth);
    const pipelineChange = formatChange(totalPipeline, openDeals.reduce((acc, d) => acc + (d.estimated_value || 0), 0) - revenueThisMonth + revenuePrevMonth);
    const avgDealChange = formatChange(avgDealSize, wonPrevMonth.length > 0 ? Math.round(wonPrevMonth.reduce((acc, d) => acc + (d.estimated_value || 0), 0) / wonPrevMonth.length) : 0);

    const pipelineByStage = [
      { name: 'Lead', value: openDeals.filter(d => d.status === 'new' || d.status === 'contacted').reduce((acc, d) => acc + (d.estimated_value || 0), 0) },
      { name: 'Qualified', value: openDeals.filter(d => d.status === 'qualified').reduce((acc, d) => acc + (d.estimated_value || 0), 0) },
      { name: 'Proposal', value: openDeals.filter(d => d.status === 'proposal').reduce((acc, d) => acc + (d.estimated_value || 0), 0) },
      { name: 'Negotiation', value: openDeals.filter(d => d.status === 'negotiation').reduce((acc, d) => acc + (d.estimated_value || 0), 0) }
    ];

    const revenueByOwnerMap: Record<string, number> = {};
    wonDeals.forEach(d => {
      const ownerId = d.owner_id;
      if (ownerId) revenueByOwnerMap[ownerId] = (revenueByOwnerMap[ownerId] || 0) + (d.estimated_value || 0);
    });
    const revenueByOwner = Object.entries(revenueByOwnerMap).map(([ownerId, value]) => {
      const member = members.find(m => m.id === ownerId);
      return { name: member ? member.name.split(' ')[0] : 'Unknown', value };
    }).sort((a, b) => b.value - a.value);

    const salesFunnel = [
      { name: 'Total Deals', value: filteredDeals.length },
      { name: 'Qualified', value: filteredDeals.filter(d => d.status === 'qualified' || d.status === 'proposal' || d.status === 'negotiation' || d.status === 'won').length },
      { name: 'Proposals', value: filteredDeals.filter(d => d.status === 'proposal' || d.status === 'negotiation' || d.status === 'won').length },
      { name: 'Negotiation', value: filteredDeals.filter(d => d.status === 'negotiation' || d.status === 'won').length },
      { name: 'Closed Won', value: wonDeals.length }
    ];

    const dealStatusDist = [
      { name: 'Open', value: openDeals.length },
      { name: 'Won', value: wonDeals.length },
      { name: 'Lost', value: lostDeals.length }
    ];

    const campaignRoi = campaigns.map(c => ({
      name: c.name.length > 15 ? c.name.substring(0, 15) + '...' : c.name,
      budget: c.budget || 0,
      spent: c.spent || 0
    }));

    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const last6Months = Array.from({ length: 6 }).map((_, i) => {
      const d = new Date();
      d.setMonth(currentMonth - (5 - i));
      return { monthIndex: d.getMonth(), year: d.getFullYear(), name: months[d.getMonth()] };
    });

    const revenueGrowth = last6Months.map(m => {
      const revInMonth = wonDeals.filter(d => {
        const closedAt = d.updated_at;
        if (!closedAt) return false;
        const closedDate = new Date(closedAt);
        return closedDate.getMonth() === m.monthIndex && closedDate.getFullYear() === m.year;
      }).reduce((acc, d) => acc + (d.estimated_value || 0), 0);
      return { name: m.name, value: revInMonth };
    });

    let runningTotal = 0;
    const cumulativeRevenueGrowth = revenueGrowth.map(item => {
      runningTotal += item.value;
      return { name: item.name, value: runningTotal };
    });

    const activePipelineVolume = last6Months.map(m => {
      const vol = filteredDeals.filter(d => {
        if (!d.created_at || d.status === 'won' || d.status === 'lost') return false;
        const createdDate = new Date(d.created_at);
        return (createdDate.getFullYear() < m.year) || (createdDate.getFullYear() === m.year && createdDate.getMonth() <= m.monthIndex);
      }).reduce((acc, d) => acc + (d.estimated_value || 0), 0);
      return { name: m.name, value: vol };
    });

    const winRateTrend = last6Months.map(m => {
      const resolvedInMonth = filteredDeals.filter(d => {
        const closedAt = d.updated_at;
        if (!closedAt || (d.status !== 'won' && d.status !== 'lost')) return false;
        const closedDate = new Date(closedAt);
        return closedDate.getMonth() === m.monthIndex && closedDate.getFullYear() === m.year;
      });
      const wonInMonth = resolvedInMonth.filter(d => d.status === 'won');
      const wr = resolvedInMonth.length > 0 ? Math.round((wonInMonth.length / resolvedInMonth.length) * 100) : 0;
      return { name: m.name, value: wr };
    });

    return {
      total_pipeline_value: { value: `$${totalPipeline.toLocaleString()}`, change: pipelineChange, trend: 'up' as const },
      total_revenue: { value: `$${totalRevenue.toLocaleString()}`, change: revenueChange, trend: 'up' as const },
      win_rate: { value: `${winRate}%`, change: winRateChange, trend: 'up' as const },
      avg_deal_size: { value: `$${avgDealSize.toLocaleString()}`, change: avgDealChange, trend: 'up' as const },
      pipeline_by_stage: pipelineByStage,
      revenue_by_owner: revenueByOwner,
      sales_funnel: salesFunnel,
      deal_status_breakdown: dealStatusDist,
      campaign_roi: campaignRoi,
      revenue_growth: cumulativeRevenueGrowth,
      active_pipeline_volume: activePipelineVolume,
      win_rate_trend: winRateTrend
    };
  }, [filteredDeals, members, campaigns]);

  useEffect(() => setIsClient(true), []);

  const handleDragEnd = (result: DropResult) => {
    if (!result.destination || !isEditMode) return;
    const items = Array.from(widgets);
    const [reorderedItem] = items.splice(result.source.index, 1);
    items.splice(result.destination.index, 0, reorderedItem);
    setWidgets(items);
  };

  const addWidget = (metric: typeof AVAILABLE_METRICS[0]) => {
    const newWidget: Widget = {
      id: `w_${Date.now()}`,
      type: metric.type as WidgetType,
      title: metric.title,
      config: { metricId: metric.id, colorTheme: '#8b5cf6' }
    };
    setWidgets([...widgets, newWidget]);
    setIsAddOpen(false);
  };

  const getWidgetGridClass = (type: WidgetType) => {
    switch (type) {
      case 'kpi': return 'col-span-1';
      case 'donut': return 'col-span-1 md:col-span-2';
      case 'funnel': return 'col-span-1 md:col-span-2';
      default: return 'col-span-1 md:col-span-2';
    }
  };

  if (!isClient) return null;

  return (
    <div className="space-y-6 overflow-hidden">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Analytics Dashboard</h1>
          <p className="text-sm text-muted-foreground">Real-time performance metrics across all client accounts.</p>
        </div>
        <div className="flex items-center gap-3">
          {isEditMode && (
            <Badge variant="secondary" className="bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-400">
              Edit Mode
            </Badge>
          )}
          {!isEditMode ? (
            <>
              <Button variant="ghost" size="sm"><Share2 className="w-4 h-4 mr-2" /> Share</Button>
              <Button variant="ghost" size="sm"><Download className="w-4 h-4 mr-2" /> Export</Button>
              <Button size="sm" onClick={() => setIsEditMode(true)}>
                <LayoutTemplate className="w-4 h-4 mr-2" /> Edit Layout
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" size="sm" onClick={() => setIsAddOpen(true)}>
                <Plus className="w-4 h-4 mr-2" /> Add Component
              </Button>
              <Button variant="ghost" size="sm" onClick={() => { setIsEditMode(false); setSelectedWidgetId(null); }}>
                Cancel
              </Button>
              <Button size="sm" onClick={() => { setIsEditMode(false); setSelectedWidgetId(null); }}>
                <Save className="w-4 h-4 mr-2" /> Save Changes
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-4">
        <span className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Filters:</span>
        <Select value={globalFilters.dateRange} onValueChange={v => setGlobalFilters(p => ({ ...p, dateRange: v }))}>
          <SelectTrigger className="w-[160px] h-9"><Calendar className="w-4 h-4 mr-2 text-muted-foreground" /><SelectValue /></SelectTrigger>
          <SelectContent><SelectItem value="7days">Last 7 Days</SelectItem><SelectItem value="30days">Last 30 Days</SelectItem><SelectItem value="thisYear">This Year</SelectItem></SelectContent>
        </Select>
        <Select value={globalFilters.pipeline} onValueChange={v => setGlobalFilters(p => ({ ...p, pipeline: v }))}>
          <SelectTrigger className="w-[160px] h-9"><Building2 className="w-4 h-4 mr-2 text-muted-foreground" /><SelectValue /></SelectTrigger>
          <SelectContent><SelectItem value="all">All Pipelines</SelectItem><SelectItem value="sales">Sales Pipeline</SelectItem></SelectContent>
        </Select>
        <Select value={globalFilters.owner} onValueChange={v => setGlobalFilters(p => ({ ...p, owner: v }))}>
          <SelectTrigger className="w-[160px] h-9"><Users className="w-4 h-4 mr-2 text-muted-foreground" /><SelectValue /></SelectTrigger>
          <SelectContent><SelectItem value="all">All Owners</SelectItem><SelectItem value="me">Assigned to Me</SelectItem></SelectContent>
        </Select>
      </div>

      {/* Widget Grid */}
      {widgets.length === 0 ? (
        <div className="text-center py-12 border-2 border-dashed rounded-lg">
          <LayoutDashboard className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
          <h3 className="text-lg font-semibold mb-2">Your Dashboard is Empty</h3>
          <p className="text-muted-foreground mb-4">Start building your custom view by adding components.</p>
          {!isEditMode && <Button onClick={() => setIsEditMode(true)}>Edit Layout</Button>}
        </div>
      ) : (
        <DragDropContext onDragEnd={handleDragEnd}>
          <Droppable droppableId="dashboard" direction="vertical" isDropDisabled={!isEditMode}>
            {(provided) => (
              <div
                {...provided.droppableProps}
                ref={provided.innerRef}
                className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 overflow-hidden"
              >
                {widgets.map((w, index) => (
                  <Draggable key={w.id} draggableId={w.id} index={index} isDragDisabled={!isEditMode}>
                    {(provided, snapshot) => (
                      <div
                        ref={provided.innerRef}
                        {...provided.draggableProps}
                        {...provided.dragHandleProps}
                        style={{
                          ...provided.draggableProps.style,
                          opacity: snapshot.isDragging ? 0.8 : 1,
                        }}
                        className={`${getWidgetGridClass(w.type)} min-w-0 ${isEditMode ? 'cursor-grab active:cursor-grabbing' : ''}`}
                      >
                        <Card className={`h-full ${isEditMode && selectedWidgetId === w.id ? 'ring-2 ring-primary' : ''}`}>
                          <CardHeader className="flex flex-row items-center justify-between pb-2">
                            <CardTitle className="text-sm font-semibold">{w.title}</CardTitle>
                            {isEditMode && (
                              <div className="flex gap-1">
                                <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => { setWidgets(widgets.filter(x => x.id !== w.id)); if (selectedWidgetId === w.id) setSelectedWidgetId(null); }}>
                                  <Trash2 className="w-3.5 h-3.5" />
                                </Button>
                                <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setSelectedWidgetId(w.id)}>
                                  <Settings className="w-3.5 h-3.5" />
                                </Button>
                              </div>
                            )}
                          </CardHeader>
                          <CardContent className="pt-0">
                            <div className={w.type === 'funnel' ? 'h-[280px]' : 'h-[200px]'}>
                              <WidgetRenderer widget={w} data={(dashboardData as Record<string, any>)[w.config.metricId]} />
                            </div>
                          </CardContent>
                        </Card>
                      </div>
                    )}
                  </Draggable>
                ))}
                {provided.placeholder}
              </div>
            )}
          </Droppable>
        </DragDropContext>
      )}

      {/* Configurator Panel */}
      {isEditMode && selectedWidgetId && (
        <div className="fixed right-0 top-0 h-full w-80 border-l bg-card shadow-lg z-40 p-5 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold">Widget Settings</h3>
            <button onClick={() => setSelectedWidgetId(null)} className="text-muted-foreground hover:text-foreground"><X className="w-4 h-4" /></button>
          </div>
          <div className="space-y-2">
            <label className="text-xs font-medium text-muted-foreground">Widget Title</label>
            <Input
              value={widgets.find(w => w.id === selectedWidgetId)?.title || ''}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setWidgets(prev => prev.map(w => w.id === selectedWidgetId ? { ...w, title: e.target.value } : w))}
            />
          </div>
          <div className="space-y-2">
            <label className="text-xs font-medium text-muted-foreground">Color Theme</label>
            <div className="flex items-center gap-2 flex-wrap">
              {Object.keys(THEME_COLORS).map(c => (
                <button
                  key={c}
                  className={`w-8 h-8 rounded-full ring-2 ring-offset-2 transition-all ${widgets.find(w => w.id === selectedWidgetId)?.config.colorTheme === c ? 'ring-primary' : 'ring-transparent hover:ring-muted-foreground/30'}`}
                  style={{ backgroundColor: c }}
                  onClick={() => setWidgets(prev => prev.map(w => w.id === selectedWidgetId ? { ...w, config: { ...w.config, colorTheme: c } } : w))}
                />
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Add Component Modal */}
      <Dialog open={isAddOpen} onOpenChange={setIsAddOpen}>
        <DialogContent className="sm:max-w-[800px] max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add Component</DialogTitle>
            <p className="text-sm text-muted-foreground">Select a metric to add to your dashboard grid.</p>
          </DialogHeader>
          <div className="space-y-8 pt-4">
            {Object.entries(METRICS_BY_TYPE).map(([category, metrics]) => (
              <div key={category} className="space-y-4">
                <h4 className="text-sm font-semibold flex items-center gap-2">
                  {category} <Badge variant="secondary">{metrics.length}</Badge>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {metrics.map(metric => (
                    <div
                      key={metric.id}
                      onClick={() => addWidget(metric)}
                      className="border rounded-lg p-4 cursor-pointer hover:border-primary hover:bg-muted/50 transition-colors group"
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-medium text-sm">{metric.title}</span>
                        <Plus className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors" />
                      </div>
                      <span className="text-xs text-muted-foreground">{metric.description}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
